### ISSUE TITLE
Project 1 Peer Review Feedback

### ISSUE THREAD

**Issue by kaylalichtner** [Bucknell-Biol364/Project_1_Group_2_2024#1]
Awesome job group 2! This tutorial is very interactive and fun! You did a great job walking one through the tutorial, it is organized well and flows in a sequence that makes sense. I also really appreciate your emphasis on graphing in this tutorial. Your code is well annotated and the explanations for the code are clear, this is a great tutorial! I have some feedback below but they are minor comments, nice job! I hope the feedback helps you!

- I think you guys mentioned having a problem with this part of the tutorial so I think you are already aware of this, but Lines 26-32 didn’t run for me 

- Not sure if this error was on my end but the code for loading in the dinosaur csv did not work for me but I could do it manually through GIT, had issues with the read.csv() versus read_csv()

- Line 93, I didn't see the table that the code was referencing?

- Love the interactive questions  piece before line 108

- LOVE the individual graphs for each dataset, beautiful and it’s organized nice with the grid function in separate columns, however I have two boxplots for dataset i?

- Great confirmation of normality with shapiro test, I also got the correct p-values for my dinosaur in dataset A!

- Add acknowledgements if you have some!

**Comment by kaylalichtner** [comment]
More feedback based on Dr. Field's message:

- I believe that your audience level is appropriate and this tutorial suits your target audience. 
- The background clearly introduces the student to the purpose and objectives of the tutorial, and the dataset is very organized and straightforward which made initial analysis digestible.  Therefore, the dataset and background motivated me as a student to complete the tutorial.
- Yes, your tutorial meets your objectives and I appreciate your emphasis on graphing and data visualization.
- Yes, I was able to complete the tutorial using your RMD file.
- Yes, it is very clear at the end if you achieved the goals as you discover whether or not you found the dinosaur!

**Comment by ashlynsak** [comment]
Thanks for the detailed feedback! A lot of your comments were just some mistakes or things out of order after multiple merges, so it was very helpful for cleaning up our code.
