### ISSUE TITLE
Peer review for both tutorial and presentation

### ISSUE THREAD

**Issue by bethwilliams150** [Bucknell-Biol364/Project_1_Group_2_2024#2]
Tutorial feedback:
I loved your tutorial! Everything went smoothly when I ran the code on my computer, and your code is neat and organized. Your instructions are informative and helpful. The way you displayed your dataset is also very visually appealing. I like that you chose the dino dataset and made it into a sort of game because it was fun and engaging, and I think anyone learning how to plot data and test hypotheses in R (such as your target audience) would enjoy this and learn a lot from it.

I also think you met most of your objectives, but I think that these should be shown at the top of your tutorial so that anyone doing your tutorial would know what they are meant to be learning (as I had to look at your "README.md" file). The only objective you didn't meet was teaching how to modify axis labels so if you add this in then it'll be good, but nice job with all your other objectives! 

My only other note is that you could have knitted the file to create a markdown (.md) document. But overall, everything you guys did was great!

Presentation feedback:
Your presentation of your code was really well done, and I don't really have any critiques of it. The presentation was done in a logical, organized manner. And all of you seemed knowledgeable on your respective parts.

**Comment by ashlynsak** [comment]
Thanks for the input! We included the objectives at the beginning of our tutorial. We also created a markdown instead of an html
